name: Deploy Next.js to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21' # Thay đổi theo phiên bản Node.js của bạn

      - name: Install dependencies
        run: npm install

      - name: Build Next.js application
        run: npm run build

      - name: Deploy to CentOS 8 Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/minimal_english_edu
            
            git config --global credential.helper store
            echo "https://${{ secrets.REPO_TOKEN }}:@github.com" > ~/.git-credentials
            git pull origin main
            
            rm -rf node_modules
            rm -rf .next
            npm install
            
            npm run build
            pm2 restart minimal_english_edu
